server:
  port: 9091
  
spring:
  application:
    name: msvc-mailsend
    
eureka:
  instance:
    hostname: localhost
  client:
    server-url: 
      defaultZone: http://localhost:${server.port}/eureka/
