server:
  port: 9090
  
spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursesdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    databa-platform: org.hibernate.dialect.PortgreSQLDialect
    
eureka:
  instance:
    hostname: localhost
  client:
    server-url: 
      defaultZone: http://localhost:${server.port}/eureka/

